### ISSUE TITLE
Joystick behaviour forA,X,Y,Z

### ISSUE THREAD

**Issue by haikew** [youseetoo/uc2-esp32#30]
Enable a feature where you can en-/disable the dual axis motion with the PS4 controller 
@beniroquai

**Comment by beniroquai** [comment]
Hey @haikew the feature can be disabled/enabled using 
```json
{"task": "/motor_act", "isDualAxisZ": 1}
```

in the new firmware. I'll push this to the uploading website https://youseetoo.github.io/ soon.
